name: Wargames Maven CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: JDK Setup
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build
        run: mvn clean install

      - name: Upload coverage to GitHub Actions
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            target/site/jacoco/jacoco.xml
